### ISSUE TITLE
Examinee take exam

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#77]
Finished delivery must satisfy:

- [ ] Examinee can see the detail of the exam before taking the exam
- [ ] Examinee can see how much time is left for the exam
- [ ] Each question has any number of questions, with 3-5 answers
- [ ] Examinee can navigate between questions
- [ ] Examinee can submit early
- [ ] Automatic scoring and storage of finished exams
- [ ] Backend: Create API for choice and un-choice answers (each examinee's choice of each question needs to be stored to database, incase the examinee disconnect)
- [ ] Fe Create Question Page

An Exam Page is available in the system

**Comment by linh442k** [comment]
Sẽ làm 2 trang exam page và question page
Khi nào có api thì @narutox900 paste vào đây 1 response mẫu mà api trả về xem

**Comment by narutox900** [comment]
ok

**Comment by tuanb11a2** [comment]
oke nha

**Comment by alitonia** [comment]
I added some data filler for questions in https://github.com/alitonia/multi-choice-system/blob/42f93ff1b4f5c3b1c35b49cfb8acba77a3a33fac/docker_data/db-config/4-exam-test-data.sql. You can use it for testing the functionality. Because these files only run on initializing, you will need to remove old db with ```bash cmd/remove_db.sh```, then ```docker-compose up``` to initialize new db. 
Do note that this version has _class_ field in Examinee table changed to _classname_ (conflict with keyword class in python).

**Comment by alitonia** [comment]
Done
